sudo: false
language: node_js
script: gulp test
node_js:
  - 5
  - 4
cache:
  directories:
    - node_modules
branches:
  only:
    - master
before_script:
  - npm install -g gulp
after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov/bin/codecov
